### PR TITLE
Simple Accounts System

### PR DESCRIPTION
**Pull request by StanLindsey**
Adds the following features using accounts-base:
1. Default user of default@admin.com with pass default@admin.
2. Auto redirects to /login if not logged in
3. Allows admins to register additional users
4. Fixes some nav bar styling. 

Todo: accounts-button.jsx uses depreciated ReactMeteorData mixin.

Other: Also removed linebreak eslint config, as otherwise every line is an error on mac/unix.

### CODE REVIEW

**Comment by tomRedox** [comment]
Awesome @StanLindsey, great job.  I'll try and look at this tomorrow but I know it's going to be a busy one so it may be the weekend before I get to it.

**Comment by tomRedox** [comment]
Hi @StanLindsey, finally got a chance to load this up on my machine, it's looking great.  Would you be able to wire up the Logout command and get that re-routing back to the login page when the user logs out?

**Comment by StanLindsey** [comment]
Ah totally thought I had that wired. I'll PR that now.

**Comment by StanLindsey** [comment]
Yeah, was wired but not pushed to origin - my fault. Give it a test now.

**Comment by tomRedox** [comment]
I may well be being stupid, but it doesn't look like today's commit includes logout code https://github.com/StanLindsey/simpleCRM/commit/21f177f6f119340a28ec09406d8cbf7d2b91b080?  I just tried it locally and it appears to not be wired up still (but this could be my inexperience with git)

**Comment by tomRedox** [comment]
Oh, now it works, sorry, I have no idea what's going on!  I've got my local repo in a muddle I think

**Comment by StanLindsey** [comment]
That last commit didn't include it, but after I pushed that to origin-master the line 13 to 17 appeared in accounts-button.jsx. (Which wasn't there before I pushed that last commit, the page asked me to refresh)

On the files changed view at the top check those lines. Are they present in your local pull? Its working locally for me. 

Edit: Nvm =P

**Pull request merged**
